# fly.toml app configuration file generated for medicsappv2 on 2023-06-27T19:10:23-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "medicsappv2"
primary_region = "qro"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
